---
# ci/boshes.yml
auth:
  https://sandbox-bosh.dev.ops.example.com:25555:
    username: admin
    password: admin
  https://staging-bosh.dev.ops.example.com:25555:
    username: admin
    password: admin
  https://prod-bosh.dev.ops.example.com:25555:
    username: admin
    password: (( vault "secret/blah/bosh:password" ))

---
# ci/settings.yml
meta:
  git:
    repo:
    branch: master




# in pipeline config

jobs:
  - task: deploy-something
    config:
      run: git/bin/genesis
      args: [ci dostuff]
    params:
      - BOSH_CONFIG: (( grab that file ))


